### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by VipinVIP** [FOSS-Cell-GECPKD/Lifetree#8]
Currently, The UI of the App seems very basic and mixed up.
![image](https://user-images.githubusercontent.com/58673683/96329730-63656080-106d-11eb-8720-6e3361532986.png)

Use a library like React-bootstrap or something to style it into a modern look with proper alignment,placing and spacing for components.

**Comment by VipinVIP** [comment]
If you can allow.. I am also interested to Work on this issue :sweat_smile:

**Comment by anandbaburajan** [comment]
> If you can allow.. I am also interested to Work on this issue

Hey @VipinVIP! Thanks for showing interest! But I think @aryanbaburajan is working on the styling part already as discussed on Gitter! :D

**Comment by VipinVIP** [comment]
Ooh.. Sorry that i didnt knew the chatroom talk.. Anyway, I think creating an issue was anyways  good :smile_cat:

**Comment by anandbaburajan** [comment]
Closing since #10 improved the UI
